### ISSUE TITLE
没有更新了

### ISSUE THREAD

**Issue by drinktoomuchsax** [Anyway-Design/Anyway-Tab#10]
新一期的节目已经出来了，但是底下提示没有更新
![image](https://user-images.githubusercontent.com/87611896/230769377-820fa7d8-47fc-45e3-8d25-be537ed12d06.png)

**Comment by drinktoomuchsax** [comment]
更新，在节目发出的第三天又有了

**Comment by JJYing** [comment]
感谢，这是个 bug，「又有了」是看了你的 issue 之后补，没有做自动化流程，我下次改进
